---
title:
author:
date:
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{table}[!htbp] \centering 
  \caption{} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\ 
\cline{2-4} 
\\[-1.8ex] & \multicolumn{3}{c}{speechiness} \\ 
\\[-1.8ex] & (1) & (2) & (3)\\ 
\hline \\[-1.8ex] 
 treatment & 0.036$^{*}$ & $-$0.160 & $-$0.160 \\ 
  & (0.021) & (0.106) & (0.106) \\ 
  & & & \\ 
 month\_trend &  &  & 0.020$^{***}$ \\ 
  &  &  & (0.006) \\ 
  & & & \\ 
 factor(release\_month)2017.02 &  & 0.160 & 0.140 \\ 
  &  & (0.104) & (0.102) \\ 
  & & & \\ 
 factor(release\_month)2017.03 &  & 0.137 & 0.097 \\ 
  &  & (0.094) & (0.090) \\ 
  & & & \\ 
 factor(release\_month)2017.04 &  & 0.349$^{***}$ & 0.288$^{***}$ \\ 
  &  & (0.094) & (0.088) \\ 
  & & & \\ 
 factor(release\_month)2017.05 &  & 0.233$^{***}$ & 0.152$^{*}$ \\ 
  &  & (0.089) & (0.082) \\ 
  & & & \\ 
 factor(release\_month)2017.06 &  & 0.270$^{***}$ & 0.169$^{**}$ \\ 
  &  & (0.090) & (0.082) \\ 
  & & & \\ 
 factor(release\_month)2017.07 &  & 0.197$^{**}$ & 0.076 \\ 
  &  & (0.090) & (0.082) \\ 
  & & & \\ 
 factor(release\_month)2017.08 &  & 0.156$^{*}$ & 0.014 \\ 
  &  & (0.088) & (0.080) \\ 
  & & & \\ 
 factor(release\_month)2017.09 &  & 0.232$^{**}$ & 0.070 \\ 
  &  & (0.091) & (0.084) \\ 
  & & & \\ 
 factor(release\_month)2017.10 &  & 0.316$^{***}$ & 0.133 \\ 
  &  & (0.097) & (0.091) \\ 
  & & & \\ 
 factor(release\_month)2017.11 &  & 0.228$^{**}$ & 0.026 \\ 
  &  & (0.089) & (0.084) \\ 
  & & & \\ 
 factor(release\_month)2017.12 &  & 0.196$^{**}$ & $-$0.026 \\ 
  &  & (0.085) & (0.081) \\ 
  & & & \\ 
 factor(release\_month)2018.01 &  & 0.293$^{***}$ & 0.050 \\ 
  &  & (0.094) & (0.068) \\ 
  & & & \\ 
 factor(release\_month)2018.02 &  & 0.418$^{***}$ & 0.155$^{*}$ \\ 
  &  & (0.137) & (0.080) \\ 
  & & & \\ 
 factor(release\_month)2018.03 &  & 0.452$^{***}$ & 0.169$^{**}$ \\ 
  &  & (0.137) & (0.076) \\ 
  & & & \\ 
 factor(release\_month)2018.04 &  & 0.451$^{***}$ & 0.147$^{**}$ \\ 
  &  & (0.136) & (0.071) \\ 
  & & & \\ 
 factor(release\_month)2018.05 &  & 0.389$^{***}$ & 0.065 \\ 
  &  & (0.134) & (0.066) \\ 
  & & & \\ 
 factor(release\_month)2018.06 &  & 0.316$^{**}$ & $-$0.028 \\ 
  &  & (0.135) & (0.065) \\ 
  & & & \\ 
 factor(release\_month)2018.07 &  & 0.418$^{***}$ & 0.054 \\ 
  &  & (0.136) & (0.067) \\ 
  & & & \\ 
 factor(release\_month)2018.08 &  & 0.429$^{***}$ & 0.044 \\ 
  &  & (0.136) & (0.064) \\ 
  & & & \\ 
 factor(release\_month)2018.09 &  & 0.431$^{***}$ & 0.026 \\ 
  &  & (0.136) & (0.064) \\ 
  & & & \\ 
 factor(release\_month)2018.10 &  & 0.354$^{***}$ & $-$0.070 \\ 
  &  & (0.137) & (0.067) \\ 
  & & & \\ 
 factor(release\_month)2018.11 &  & 0.473$^{***}$ & 0.028 \\ 
  &  & (0.137) & (0.068) \\ 
  & & & \\ 
 factor(release\_month)2018.12 &  & 0.465$^{***}$ &  \\ 
  &  & (0.136) &  \\ 
  & & & \\ 
 factor(class)hiphop & 0.242$^{***}$ & 0.238$^{***}$ & 0.238$^{***}$ \\ 
  & (0.039) & (0.038) & (0.038) \\ 
  & & & \\ 
 factor(class)pop & $-$0.006 & $-$0.009 & $-$0.009 \\ 
  & (0.037) & (0.037) & (0.037) \\ 
  & & & \\ 
 factor(class)rock & 0.099$^{**}$ & 0.090$^{*}$ & 0.090$^{*}$ \\ 
  & (0.048) & (0.048) & (0.048) \\ 
  & & & \\ 
 Constant & 0.354$^{***}$ & 0.141$^{*}$ & 0.384$^{***}$ \\ 
  & (0.035) & (0.078) & (0.077) \\ 
  & & & \\ 
\hline \\[-1.8ex] 
Observations & 1,158 & 1,158 & 1,158 \\ 
R$^{2}$ & 0.095 & 0.123 & 0.123 \\ 
Adjusted R$^{2}$ & 0.092 & 0.102 & 0.102 \\ 
Residual Std. Error & 0.358 (df = 1153) & 0.356 (df = 1130) & 0.356 (df = 1130) \\ 
F Statistic & 30.200$^{***}$ (df = 4; 1153) & 5.860$^{***}$ (df = 27; 1130) & 5.860$^{***}$ (df = 27; 1130) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table} 